### ISSUE TITLE
How to make the thumbnail's text display two lines?

### ISSUE THREAD

**Issue by Marina-Ma** [teobais/thodorisbais2.github.io#6]
Hello,

I use the same theme. it seems that you make the thumbnail's text display only 15 words, how to achieve that?

My Github
https://github.com/Marina-Ma/Marina-Ma.github.io

My Blog
https://marina-ma.github.io/

Many thanks.

**Comment by teobais** [comment]
Hello,

this can happen [using the `truncatewords` property](https://github.com/toubou91/toubou91.github.io/blob/master/index.html#L12).

TB

**Comment by Marina-Ma** [comment]
The problem appears when the text is written in Chinese.
Here is the solution but I still don't know how to revise the code :cry: 

[Fix truncate to work with non Latin characters](https://github.com/petetak/liquid/commit/80eacde8b03697de0e44aaf442052fb2fc15377f)

[Make "truncatewords" and "truncate" work for non-English characters](https://github.com/Shopify/liquid/issues/166)

**Comment by Marina-Ma** [comment]
It has been solved when the code is changed to ```{{post.content | strip_html | truncate:200}}```

Thanks

**Comment by teobais** [comment]
Good to know, nice.
